services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    ports: [ "8545:8545" ]
    entrypoint: [ "anvil", "--fork-url", "${ANVIL_FORK_URL}", "--chain-id", "1", "--host", "0.0.0.0", "--fork-block-number", "24383419"]